# fly.toml app configuration file generated for spokanetech-py on 2024-01-31T20:22:30-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spokanetech-py'
primary_region = 'sea'
console_command = '/code/src/manage.py shell'

[build]

[env]
  PORT = '8000'

[processes]
  app = 'gunicorn --chdir ./src --bind :8000 --workers 2 spokanetech.wsgi'
  wokrer = 'python -m celery --workdir ./src -A spokanetech.celery worker -B -l INFO'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[deploy]
  release_command = "./scripts/post_deploy.sh"
