[tool.bandit]
exclude_dirs = [".venv", "venv", "src/*/tests"]


[tool.black]
line-length = 120
exclude = """manage.py|migrations"""


[tool.ruff]
line-length = 120
exclude = ["src/*/migrations", "src/manage.py"]
