on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "Run Bandit"
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: Run Bandit
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          args: "--src src --req requirements.txt bandit --pyproject pyproject.toml"
          version: "0.10.2"
