on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    name: "bandit"
    steps:
      - uses: davidslusser/actions_python_bandit@v1.0.0
        with:
          src: "src"
          options: "-c pyproject.toml -r"
          python_version: "3.11"
