name: Deploy spokanetech-worker to azure

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/deploy_worker_azure.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: spokanetech-worker
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/spokanetech-worker:latest
          environmentVariables: |
            CELERY_BROKER_URL=secretref:celery-broker-url
            EVENTBRITE_API_TOKEN=secretref:eventbrite-api-token
            SENTRY_DSN=secretref=sentry-dsn
            DJANGO_SECRET_KEY=secretref:django-secret-key
            DATABASE_URL=secretref:database-url
            DISCORD_WEBHOOK_URL=secretref:discord-webhook-url
            USE_AZURE=false
