name: Deploy Docs

on:
  push:
    branches: 
      - main
    paths:
      - '/docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements/dev.txt
      - run: mkdocs gh-deploy --force
