on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.9.8 sh; cd -; }
      - name: Run Dagger pipeline
        run: dagger call --mod ci/ lint --dir .
