name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '/docs/**'
      - 'mkdocs.yml'

env:
  DJANGO_SECRET_KEY: noop
  CELERY_BROKER_URL: noop
  DISCORD_WEBHOOK_URL: noop
  USE_AZURE: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements.txt -r requirements/dev.txt
      - run: pytest -vv --config-file=pyproject.toml src
